AWSTemplateFormatVersion: "2010-09-09"
Description: To create EC2 instance

Resources:

  DemoEC2Instance:
    Type: AWS::EC2::Instance
    Properties:
      KeyName: key1
      ImageId: ami-0df7a207adb9748c7 #Ubuntu
      AvailabilityZone: ap-southeast-1a
      InstanceType: t2.micro
      Tags:
        - Key: env
          Value: test
        - Key: Name
          Value: TS-Instance
